### ISSUE TITLE
Update the Readme.md

### ISSUE THREAD

**Issue by arghac14** [arghac14/DataStructure-and-Algorithms#7]
Update the Readme.md file and provide links and details to every data structure and algorithms that have been implemented.

**Comment by papageop** [comment]
Can I work on this?

**Comment by arghac14** [comment]
@papageop yeah sure! go for it.

**Comment by SparshKat** [comment]
Hi @arghac14 , i have updated the README with approporiate code snippet and DRY formatting for better and understandable readme . PR -> #22
